def __init__(self, parent = None) :
	super(myWindow, self).__init__(parent)
	self.pushButton = QtGui.QPushButton(self)
	self.pushButton.setText("Send Log Message")
	self.pushButton.clicked.connect(self.on_pushButton_clicked)
	self.pushButtonThread = QtGui.QPushButton(self)
	self.pushButtonThread.setText("Start Threading")
	self.pushButtonThread.clicked.connect(self.on_pushButtonThread_clicked)
	self.lineEdit = QtGui.QLineEdit(self)
	self.lineEdit.setText("Hello!")
	self.label = QtGui.QLabel(self)
	self.layout = QtGui.QVBoxLayout(self)
	self.layout.addWidget(self.lineEdit)
	self.layout.addWidget(self.pushButton)
	self.layout.addWidget(self.pushButtonThread)
	self.layout.addWidget(self.label)
	self.logBuffer = logBuffer()
	self.logBuffer.bufferMessage.connect(self.on_logBuffer_bufferMessage)
	logFormatter = logging.Formatter('%(levelname)s: %(message)s')
	logHandler = logging.StreamHandler(self.logBuffer)
	logHandler.setFormatter(logFormatter)
	self.logger = logging.getLogger()
	self.logger.setLevel(logging.INFO)
	self.logger.addHandler(logHandler)
	self.thread = myThread(self)
	self.thread1 = myThread1(self)




def __init__(self, parent = None) :
	super(myWindow, self).__init__(parent)
	self.pushButton = QtGui.QPushButton(self)
	self.pushButton.setText("Send Log Message")
	self.pushButton.clicked.connect(self.on_pushButton_clicked)
	self.pushButtonThread = QtGui.QPushButton(self)
	self.pushButtonThread.setText("Start Threading")
	self.pushButtonThread.clicked.connect(self.on_pushButtonThread_clicked)
	self.lineEdit = QtGui.QLineEdit(self)
	self.lineEdit.setText("Hola!")
	self.label = QtGui.QLabel(self)
	self.layout = QtGui.QVBoxLayout(self)
	self.layout.addWidget(self.lineEdit)
	self.layout.addWidget(self.pushButton)
	self.layout.addWidget(self.pushButtonThread)
	self.layout.addWidget(self.label)
	self.logBuffer = logBuffer()
	self.logBuffer.bufferMessage.connect(self.on_logBuffer_bufferMessage)
	logFormatter = logging.Formatter('%(levelname)s: %(message)s')
	logHandler = logging.StreamHandler(self.logBuffer)
	logHandler.setFormatter(logFormatter)
	self.logger = logging.getLogger()
	self.logger.setLevel(logging.INFO)
	self.logger.addHandler(logHandler)
	self.thread = myThread1(self)
	self.thread1 = myThread3(self)
